# 站点基本信息
title: "我的个人网站"
description: "读书笔记 · 杂文随想 · 个人介绍"
url: "https://你的GitHub用户名.github.io"
baseurl: "" # 根目录

# 使用 Minimal Mistakes 主题
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: default # 主题配色，可改 "dark", "air", "contrast"

# 插件
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3 # 自动目录层级

# 导航菜单
navigation:
  - title: "首页"
    url: /
  - title: "读书笔记"
    url: /notes/
  - title: "杂文随想"
    url: /essays/
  - title: "个人介绍"
    url: /about/

# 分类显示设置
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# 搜索设置
search: true

# 作者信息
author:
  name: "你的名字"
  bio: "这是我的个人简介。"
  location: "中国"
  email: "你的邮箱"

# 默认 Front Matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

