# 基本信息
title: "Alexistsui"
description: "读书笔记 · 杂文随想 · 个人介绍"
url: "https://alexistsui94.github.io"
baseurl: "" # 根目录

# 主题
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: default # 可选: dark, air, contrast

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# 分页
paginate: 5
paginate_path: "/page:num/"

# 搜索
search: true

# 作者
author:
  name: "你的名字"
  bio: "个人简介"
  email: "你的邮箱"

# 让 _pages 集合参与构建并输出到站点
collections:
  pages:
    output: true
    permalink: /:path/

# 默认文章和页面设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
