# ------------------ 基本站点信息 ------------------
title: "Alexistsui"
description: "读书笔记 · 杂文随想 · 个人介绍"
url: "https://alexistsui94.github.io"   # 你的 GitHub Pages 域名
baseurl: ""                             # 根路径，用户主页仓库保持空
locale: "zh-CN"
timezone: "Asia/Shanghai"

# ------------------ 主题与样式 ------------------
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"  # 可改：dark, air, contrast 等

# ------------------ 生成与 Markdown ------------------
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3

permalink: /:categories/:title/   # 更好看的文章链接
paginate: 5
paginate_path: "/page:num/"

# ------------------ 插件（均为 GitHub Pages 支持） ------------------
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# ------------------ 导航（使用 _data/navigation.yml） ------------------
# 你已经在 _data/navigation.yml 中维护菜单，这里无需额外配置

# ------------------ 搜索 ------------------
search: true

# ------------------ 作者信息（按需修改） ------------------
author:
  name: "你的名字"
  bio: "个人简介"
  email: "你的邮箱"

# ------------------ 归档页（分类 / 标签） ------------------
# /categories/ 和 /tags/ 两个索引页由 _pages 里对应文件生成
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# ------------------ 默认 Front Matter ------------------
defaults:
  # 文章默认配置（_posts 下的内容）
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true

  # 独立页面（_pages 下的内容）默认使用单页布局
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# ------------------ 站点增强（可选） ------------------
# 下面这些是 Minimal Mistakes 的常用开关，按需调整
logo:                        # 可放站点 logo（/assets/images/logo.png）
breadcrumbs: false           # 面包屑
toc: true                    # 全局是否启用目录（页面里可单独关闭/开启）
toc_sticky: true
