# force rebuild 2025-08-09
# 基本信息
title: "Alexisxu"
description: "读书笔记 · 杂文随想 · 个人介绍"
url: "https://alexistsui94.github.io"
baseurl: "" # 根目录

# 主题
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: default # 可选: dark, air, contrast

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# 分页
paginate: 5
paginate_path: "/page:num/"

# 搜索
search: false

# 作者
author:
  name:
  bio:
  email:

# 让 _pages 集合参与构建并输出到站点
collections:
  pages:
    output: true
    permalink: /:path/

# 默认文章和页面设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_next: false
      show_previous: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      show_next: false
      show_previous: false

# 自定义 CSS
sass:
  style: compressed

# 加载自定义
include:
  - assets/css

# 自定义样式覆盖
custom_css:
  - /assets/css/custom.css
